name: "Bug report"
description: "Report something that is broken"
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: The button did nothing when I clicked...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Browser/OS/Node version"
  - type: checkboxes
    id: checks
    attributes:
      label: Confirm
      options:
        - label: I searched existing issues
          required: true
        - label: I can work on this