blank_issues_enabled: true
contact_links:
  - name: Questions / Help
    url: https://github.com/YashSakhareliya/SuperPoll/discussions
    about: Ask usage questions here (enable Discussions or adjust this link)
